server:
  port: 11090

spring:
  application:
    name: swagger-register

logging:
  path: ./logs
  level:
    root: info

---
spring:
  profiles: dev

logging:
  path: /logs
  level:
    root: info

