server:
  port: 11090

spring:
  application:
    name: swagger-register

#注册服务数据保存路径
swagger:
  register-data-path: ./register-data

logging:
  path: ./logs
  level:
    root: info

---
spring:
  profiles: dev

swagger:
  register-data-path: /register-data

logging:
  path: /logs
  level:
    root: info

